In [1]:
from Element2_Pandas import*

# Oppgaver

# Oppgave 1:
Har importert filen 2342202.csv i python-filen og kalt den for "df_opg1"

# Oppgave 2:

Vi ser at dataen er organisert i 92099 rader og fire kolonner: Station, Name, Date og TAVG.
Datasettet består av datatypene "object" og "float64" hvor TAVG består av "float64"-verdier og resten er "object".

NB! Legger også merke til at i TAVG kolonnen så finnes det bare 7606 rader som ikke er null-verdier.

In [2]:
df_opg1.head()

STATION                         NAME        DATE  TAVG
0  US1NYWC0003  WHITE PLAINS 3.1 NNW, NY US  2017-01-03   NaN
1  US1NYWC0003  WHITE PLAINS 3.1 NNW, NY US  2017-01-04   NaN
2  US1NYWC0003  WHITE PLAINS 3.1 NNW, NY US  2017-01-05   NaN
3  US1NYWC0003  WHITE PLAINS 3.1 NNW, NY US  2017-01-06   NaN
4  US1NYWC0003  WHITE PLAINS 3.1 NNW, NY US  2017-01-09   NaN

In [3]:
df_opg1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92099 entries, 0 to 92098
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   STATION  92099 non-null  object 
 1   NAME     92099 non-null  object 
 2   DATE     92099 non-null  object 
 3   TAVG     7606 non-null   float64
dtypes: float64(1), object(3)
memory usage: 2.8+ MB


# oppgave 3:
Dropper duplikerte rader og rader med null-verdier vha. "drop_dup_nan" funksjonen, og fikser index-verdiene vha. "fix_index" funksjonen.

Vi ser at det nå er kun 7606 gjenværende rader i df_opg1. Dette er fordi at en stor majoritet av de 92099 radene i TAVG-kolonnen inneholdt null-verdier.

In [4]:
drop_dup_nan(df_opg1)
fix_index(df_opg1)
df_opg1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7606 entries, 0 to 7605
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   STATION  7606 non-null   object 
 1   NAME     7606 non-null   object 
 2   DATE     7606 non-null   object 
 3   TAVG     7606 non-null   float64
dtypes: float64(1), object(3)
memory usage: 237.8+ KB


# Oppgave 4:
deler "NAME" kolonnen i to kolonner "Area" og "Country" vha. funksjonen "split_NAME" fra spyder-filen.

PS! Funksjonen gir feilmelding om at NAME-kolonnen ikke finnes om funksjonen blir kjørt flere ganger, fordi NAME-kolonnen fjernes etter første gang den kjøres.



In [5]:
split_NAME(df_opg1)
df_opg1.head()

STATION        DATE  TAVG               AREA COUNTRY
0  USW00014732  2017-01-01  46.0  LAGUARDIA AIRPORT   NY US
1  USW00014732  2017-01-02  40.0  LAGUARDIA AIRPORT   NY US
2  USW00014732  2017-01-03  42.0  LAGUARDIA AIRPORT   NY US
3  USW00014732  2017-01-04  47.0  LAGUARDIA AIRPORT   NY US
4  USW00014732  2017-01-05  34.0  LAGUARDIA AIRPORT   NY US

# Oppgave 5:
Vi deler COUNTRY-kolonnen i to kolonner CITY og COUNTRY vha. "split_COUNTRY" funksjonen 

In [6]:
split_COUNTRY(df_opg1)
df_opg1.head()

STATION        DATE  TAVG               AREA COUNTRY CITY
0  USW00014732  2017-01-01  46.0  LAGUARDIA AIRPORT      US   NY
1  USW00014732  2017-01-02  40.0  LAGUARDIA AIRPORT      US   NY
2  USW00014732  2017-01-03  42.0  LAGUARDIA AIRPORT      US   NY
3  USW00014732  2017-01-04  47.0  LAGUARDIA AIRPORT      US   NY
4  USW00014732  2017-01-05  34.0  LAGUARDIA AIRPORT      US   NY

# Oppgave 6: 
Vi har laget en funksjon "fix_COUNTRY" for å endre "COUNTRY"-kolonnen til landskoder på to bokstaver. I df_opg1 trengs ikke denne fordi vi allerede har gjort "COUNTRY"-kolonnen til landskoder på to bokstaver.

# Oppgave 7:
I spyder-filen har vi importert filen "2342207.csv", og kalt den for "df_opg7". Vi har også definert en funksjon "trinn_3_4_6" for å gjøre trinn 3, 4 og 6.

In [7]:
trinn_3_4_6(df_opg7)
df_opg7.head()

STATION      DATE  TAVG             AREA COUNTRY
0  FIE00142101  1/1/2017  33.0  HELSINKI ILMALA      FI
1  FIE00142101  1/2/2017  26.0  HELSINKI ILMALA      FI
2  FIE00142101  1/3/2017  21.0  HELSINKI ILMALA      FI
3  FIE00142101  1/4/2017   9.0  HELSINKI ILMALA      FI
4  FIE00142101  1/5/2017   1.0  HELSINKI ILMALA      FI

# Oppgave 8:
Bruker funksjonen "combine_dfs" fra spyder-filen for å sette sammen df_opg1 og df_opg7 til en df_opg8, og for å fikse index-verdiene til den resulterende df-en.

In [8]:
df_opg8 = combine_dfs(df_opg1, df_opg7)

In [9]:
df_opg8.head()

STATION        DATE  TAVG               AREA COUNTRY CITY
0  USW00014732  2017-01-01  46.0  LAGUARDIA AIRPORT      US   NY
1  USW00014732  2017-01-02  40.0  LAGUARDIA AIRPORT      US   NY
2  USW00014732  2017-01-03  42.0  LAGUARDIA AIRPORT      US   NY
3  USW00014732  2017-01-04  47.0  LAGUARDIA AIRPORT      US   NY
4  USW00014732  2017-01-05  34.0  LAGUARDIA AIRPORT      US   NY

# Oppgave 9:
For å kontrollere at df-en fra trinn 8 er riktig kan vi sjekke at lengden på df-en fra trinn 8 er lik summen av lengdene til de to tidligere df-ene som den består av.

Dette har vi laget en funksjon for i Spyder-filen kalt "kontroll". 

Funksjonen printer "Riktig lengde" om lengden til de to tidligere df-ene samsvarer med lengden på df_opg8.

In [10]:
kontroll(df_opg1, df_opg7, df_opg8)

Riktig lengde


# Oppgave 11:
I spyder-filen har vi importert alle filene fra "weather"-mappen og lagret dem i en liste kalt "all_dfs".

Vi har også definert en funksjon "fix_dfs_in_list" som kjører trinn 3, 4 og 6 for hver df i en liste.


In [11]:
fix_dfs_in_list(all_dfs)

# Oppgave 12:
I spyder-filen har vi importert "Trondheim.csv"-filen og kalt den "df_trondheim"

In [12]:
trinn_3_4_6(df_trondheim)

#  Oppgave 13:
Lager en ny kolonne TAVG som er gjennomsnittet av TMIN og TMAX:


In [13]:
df_trondheim["TAVG"] = (df_trondheim["TMIN"]+df_trondheim["TMAX"])/2

# Oppgave 14:
Endrer df_trondheim slik at rekkefølgen er lik rekkefølgen til de andre df-ene, og slik at "TMIN" og "TMAX" ikke blir med. 

Dette gjøres vha. definisjonen "df_make_default" 


In [14]:
df_trondheim = df_make_default(df_trondheim)


In [15]:
df_trondheim.head()

STATION        DATE  TAVG            AREA COUNTRY
0  NOE00111040  2017-01-01  34.0  TRONDHEIM VOLL      NO
1  NOE00111040  2017-01-02  30.5  TRONDHEIM VOLL      NO
2  NOE00111040  2017-01-03  30.5  TRONDHEIM VOLL      NO
3  NOE00111040  2017-01-04  20.5  TRONDHEIM VOLL      NO
4  NOE00111040  2017-01-05  14.0  TRONDHEIM VOLL      NO

# Oppgave 15:
Skal kombinere alle df-ene til en større df kalt "df_complete".
Vi har definert en funksjon "making_of_df_complete" som kombinerer df-ene fra listen "all_dfs" samt "df_trondheim" til en df kalt "df_complete".

In [16]:
df_complete = making_of_df_complete()

In [17]:
df_complete.head()

STATION      DATE  TAVG        AREA COUNTRY  TMAX  TMIN
0  DEW00035032  1/1/2017  26.0  RHIEN MAIN      DE   NaN   NaN
1  DEW00035032  1/2/2017  32.0  RHIEN MAIN      DE   NaN   NaN
2  DEW00035032  1/3/2017  34.0  RHIEN MAIN      DE   NaN   NaN
3  DEW00035032  1/4/2017  37.0  RHIEN MAIN      DE   NaN   NaN
4  DEW00035032  1/5/2017  31.0  RHIEN MAIN      DE   NaN   NaN

# Oppgave 16:
importerer "countryContinent.csv" til en df kalt "df_country_continent"

In [18]:
df_country_continent = pd.read_csv('Datasets/countryContinent.csv', encoding="iso_8859_1")

# Oppgave 17:
Vi kan se at df_country_continent er strukturert i 9 kolonner. 

Kolonnene inneholder informasjon om land, som hvilke region de befinner seg i, regions-koden og lands-koden osv. 

Blant all denne informasjonen er det mye som kan være unyttig når vi skal se på temperaturdata. Det som kan være nyttig å vite derimot er: land, lands-kode, kontinent og region. Fordi denne informasjonen er relevant til temperaturdataen.

In [19]:
df_country_continent.head(10)

country code_2 code_3  country_code     iso_3166_2 continent  \
0          Afghanistan     AF    AFG             4  ISO 3166-2:AF      Asia   
1        Åland Islands     AX    ALA           248  ISO 3166-2:AX    Europe   
2              Albania     AL    ALB             8  ISO 3166-2:AL    Europe   
3              Algeria     DZ    DZA            12  ISO 3166-2:DZ    Africa   
4       American Samoa     AS    ASM            16  ISO 3166-2:AS   Oceania   
5              Andorra     AD    AND            20  ISO 3166-2:AD    Europe   
6               Angola     AO    AGO            24  ISO 3166-2:AO    Africa   
7             Anguilla     AI    AIA           660  ISO 3166-2:AI  Americas   
8           Antarctica     AQ    ATA            10  ISO 3166-2:AQ       NaN   
9  Antigua and Barbuda     AG    ATG            28  ISO 3166-2:AG  Americas   

        sub_region  region_code  sub_region_code  
0    Southern Asia        142.0             34.0  
1  Northern Europe        150.0            154.0  
2  Southern Europe        150.0             39.0  
3  Northern Africa          2.0             15.0  
4        Polynesia          9.0             61.0  
5  Southern Europe        150.0             39.0  
6    Middle Africa          2.0             17.0  
7        Caribbean         19.0             29.0  
8              NaN          NaN              NaN  
9        Caribbean         19.0             29.0

# Oppgave 18:
Bruker "merge" funksjonen til å slå sammen "df_complete" og "df_country_continent" til en df "df_complete_cont".

Vi slår de sammen med hensyn på kolonnene "COUNTRY" (fra "df_complete") og "code_2" (fra "df_country_continent"), fordi disse kolonnene samsvarer.


In [20]:
df_complete_cont = pd.merge(df_complete, df_country_continent, left_on="COUNTRY", right_on="code_2")

# Oppgave 19:
Har definert en funksjon "trinn19()" i spyder-filen som dropper kolonnen "code_2", og gir nye navn til de forespurte kolonnene. 

In [21]:
df_complete_cont = trinn19(df_complete_cont)

# Oppgave 21:
Vi har definert en funksjon i spyder-filen "column_values()" som finner, sorterer og returnerer alle unike verdier fra en kolonne i en dataframe. 

Her har vi tatt i bruk de innebygde pandas funksjonene "sort_values()" og "unique()" for å kun ta med unike navn på land og for å sortere listen alfabetisk.

Alternativt kunne man enkelt ha definert en funksjon for dette på egenhånd også på måten vist under. Her definerer vi først en tom liste "unike_land", og går så gjennom hvert land i kolonnen "Country" i "df_complete_cont". Om landet ikke allerede finnes i listen "unike_land" så adder vi det til listen. Deretter bruker vi den innebygde python-funksjonen "sorted()" til å sortere listen alfabetisk:



unike_land = []

for land in list(df_complete_cont["Country"]):
    
    if land not in unike_land:
        
        unike_land.append(land)

unike_land = sorted(unike_land)



In [22]:
countries_in_df = column_values(df_complete_cont, "Country")
continents_in_df = column_values(df_complete_cont, "Continent")

# Oppgave 22:
Vi har definert en funksjon "c_to_f()" i spyder som konverterer grader i celcius til grader i fahrenheit. Vi bruker den til å konvertere alle verdiene i kolonnen "TAVG" til fahrenheit.

Konvertere en blanding av verdier i Celsius og Fahrenheit til Fahrenheit: 
Først og fremst måtte man sjekket om verdiene var målt i Celcius eller i Fahrenheit. Vi vet at alle temperaturer over 56.7 grader må være målt i fahrenheit, med mindre de har satt en ny varmerekord. Videre så kunne man sammenlignet hver temperatur med gjennomsnittstemperaturen 

In [26]:
df_complete_cont["TAVG"] = c_to_f(df_complete_cont["TAVG"])

In [29]:
print(df_complete_cont["TAVG"].min())

-29.2


In [1]:
import os
os.getcwd()

'C:\\Users\\fredr\\Documents\\RPi\\prosjekt'